-- ====================================================================
-- LynkerAI 用户行为追踪 & 情绪识别模块
-- User Events + Emotion Analysis Module
-- ====================================================================

-- 创建用户行为日志表
CREATE TABLE IF NOT EXISTS public.user_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  event_payload JSONB DEFAULT '{}'::jsonb,
  emotion_label TEXT,
  emotion_score NUMERIC(4,3),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 创建用户画像表
CREATE TABLE IF NOT EXISTS public.user_insights (
  user_id BIGINT PRIMARY KEY,
  top_concerns TEXT[] DEFAULT '{}',
  emotion_tendency TEXT DEFAULT 'neutral',
  last_7d_event_count INT DEFAULT 0,
  push_ready BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 启用行级安全 (RLS)
ALTER TABLE public.user_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_insights ENABLE ROW LEVEL SECURITY;

-- 删除旧策略（如果存在）
DROP POLICY IF EXISTS p_user_events_all ON public.user_events;
DROP POLICY IF EXISTS p_user_insights_all ON public.user_insights;

-- 创建访问策略（允许后端读写）
CREATE POLICY p_user_events_all ON public.user_events
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY p_user_insights_all ON public.user_insights
  FOR ALL USING (true) WITH CHECK (true);

-- 完成提示
SELECT 'user_events 表创建成功' AS status;
SELECT 'user_insights 表创建成功' AS status;
