-- LynkerAI TMS (Trusted Metaphysics System) 数据库架构
-- 假名制 × 真命盘验证 × 区域适配 × 置信投票

-- 1️⃣ 用户档案表（假名制）
CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudonym TEXT UNIQUE NOT NULL,
    region_code TEXT,
    environment_tags TEXT[],
    school_tag TEXT[],
    ai_signature TEXT,
    verified_chart BOOLEAN DEFAULT FALSE,
    confidence_score NUMERIC(5,2) DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 2️⃣ 已验证命盘表（TMS专用）
CREATE TABLE IF NOT EXISTS tms_verified_charts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES user_profiles(id) ON DELETE CASCADE,
    chart_hash TEXT UNIQUE NOT NULL,
    chart_type TEXT NOT NULL,
    region TEXT,
    climate TEXT,
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    schema_version TEXT DEFAULT 'v1.0',
    verification_method TEXT DEFAULT 'signature',
    verifier_ai TEXT,
    confidence_level NUMERIC(5,2) DEFAULT 0.0,
    verified_at TIMESTAMP DEFAULT NOW(),
    
    CONSTRAINT valid_confidence CHECK (confidence_level >= 0 AND confidence_level <= 100)
);

-- 3️⃣ 验证记录表（可追溯性）
CREATE TABLE IF NOT EXISTS verification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chart_id BIGINT REFERENCES tms_verified_charts(id) ON DELETE CASCADE,
    verifier_type TEXT NOT NULL,
    verifier_id TEXT NOT NULL,
    action TEXT NOT NULL,
    signature TEXT,
    result TEXT,
    confidence_delta NUMERIC(5,2),
    timestamp TIMESTAMP DEFAULT NOW()
);

-- 4️⃣ 置信投票表（多 Child AI 共识机制）
CREATE TABLE IF NOT EXISTS confidence_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chart_id BIGINT REFERENCES tms_verified_charts(id) ON DELETE CASCADE,
    voter_ai TEXT NOT NULL,
    vote_type TEXT NOT NULL CHECK (vote_type IN ('approve', 'reject', 'uncertain')),
    confidence_score NUMERIC(5,2),
    vote_reason TEXT,
    voted_at TIMESTAMP DEFAULT NOW(),
    
    UNIQUE(chart_id, voter_ai)
);

-- 5️⃣ 区域适配配置表
CREATE TABLE IF NOT EXISTS regional_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code TEXT UNIQUE NOT NULL,
    region_name TEXT,
    timezone TEXT,
    default_calendar TEXT,
    climate_type TEXT,
    latitude_range NUMRANGE,
    longitude_range NUMRANGE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 6️⃣ AI 节点注册表（Child AI 管理）
CREATE TABLE IF NOT EXISTS ai_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id TEXT UNIQUE NOT NULL,
    node_type TEXT NOT NULL CHECK (node_type IN ('master', 'child', 'validator')),
    public_key TEXT,
    region_code TEXT,
    specialization TEXT[],
    trust_score NUMERIC(5,2) DEFAULT 50.0,
    active BOOLEAN DEFAULT TRUE,
    last_heartbeat TIMESTAMP,
    registered_at TIMESTAMP DEFAULT NOW()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_tms_user_pseudonym ON user_profiles(pseudonym);
CREATE INDEX IF NOT EXISTS idx_tms_chart_hash ON tms_verified_charts(chart_hash);
CREATE INDEX IF NOT EXISTS idx_tms_chart_region ON tms_verified_charts(region);
CREATE INDEX IF NOT EXISTS idx_verification_logs_chart ON verification_logs(chart_id);
CREATE INDEX IF NOT EXISTS idx_votes_chart ON confidence_votes(chart_id);
CREATE INDEX IF NOT EXISTS idx_ai_nodes_type ON ai_nodes(node_type);

-- 插入默认区域配置示例
INSERT INTO regional_configs (region_code, region_name, timezone, default_calendar, climate_type)
VALUES 
    ('CN', '中国', 'Asia/Shanghai', 'lunar', 'temperate'),
    ('US', '美国', 'America/New_York', 'gregorian', 'varied'),
    ('IN', '印度', 'Asia/Kolkata', 'vedic', 'tropical')
ON CONFLICT (region_code) DO NOTHING;

-- 插入 Master AI 节点
INSERT INTO ai_nodes (node_id, node_type, public_key, trust_score, active)
VALUES 
    ('master_ai_001', 'master', 'master_public_key_placeholder', 100.0, TRUE)
ON CONFLICT (node_id) DO NOTHING;
