
export const mockAnnualFortuneData = {
  2023: {
    year: 2023,
    months: [
      {
        month: 1,
        overallScore: 65,
        overallDescription: '新年伊始，运势平稳上升。适合制定新的计划和目标。',
        careerScore: 70,
        careerDescription: '工作机遇增多，但需要谨慎把握。',
        loveScore: 60,
        loveDescription: '感情运平稳，单身者有机会遇见心仪之人。',
        wealthScore: 65,
        wealthDescription: '财运稳定，适合保守投资。',
        healthWarning: {
          level: 'low',
          description: '整体健康状况良好，无特殊预警。',
          suggestions: ['保持规律作息', '适度运动', '均衡饮食'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月无重大凶险，可放心行动。',
          suggestions: ['出行注意安全', '避免冲动消费', '谨慎签署合同'],
        },
      },
      {
        month: 2,
        overallScore: 72,
        overallDescription: '春节期间运势良好，家庭和睦，事业顺利。',
        careerScore: 75,
        careerDescription: '职场表现突出，有升职加薪的机会。',
        loveScore: 68,
        loveDescription: '感情甜蜜，已婚者家庭和谐。',
        wealthScore: 70,
        wealthDescription: '财运旺盛，有意外收获。',
        healthWarning: {
          level: 'low',
          description: '春节期间注意饮食，避免过度劳累。',
          suggestions: ['控制饮食', '适度休息', '避免熬夜'],
        },
        disasterWarning: {
          level: 'medium',
          description: '春节出行需注意交通安全。',
          suggestions: ['避免长途驾驶', '提前规划路线', '购买保险'],
        },
      },
      {
        month: 3,
        overallScore: 68,
        overallDescription: '春暖花开，运势稳定。适合开展新项目。',
        careerScore: 70,
        careerDescription: '工作进展顺利，团队合作良好。',
        loveScore: 65,
        loveDescription: '感情稳定，可考虑进一步发展。',
        wealthScore: 68,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '春季易感冒，注意增减衣物。',
          suggestions: ['适应气候变化', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨慎投资', '避免冲动决定', '保持低调'],
        },
      },
      {
        month: 4,
        overallScore: 70,
        overallDescription: '清明时节，运势继续上升。适合出行和社交。',
        careerScore: 72,
        careerDescription: '职场机遇增多，人脉拓展良好。',
        loveScore: 70,
        loveDescription: '感情运势上升，有结婚的可能。',
        wealthScore: 72,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '清明时节气候多变，注意保暖。',
          suggestions: ['避免过度劳累', '适度运动', '调理脾胃'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['出行注意安全', '避免争执', '保持谦虚'],
        },
      },
      {
        month: 5,
        overallScore: 75,
        overallDescription: '五月运势最佳，各方面都有突破。',
        careerScore: 80,
        careerDescription: '职场表现优异，有重要机遇出现。',
        loveScore: 75,
        loveDescription: '感情甜蜜，有结婚或订婚的可能。',
        wealthScore: 78,
        wealthDescription: '财运旺盛，投资收益显著。',
        healthWarning: {
          level: 'low',
          description: '五月天气炎热，注意防暑降温。',
          suggestions: ['避免中暑', '多喝水', '适度休息'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势最佳，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 6,
        overallScore: 72,
        overallDescription: '初夏时节，运势稳定。适合巩固成果。',
        careerScore: 75,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 70,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 70,
        wealthDescription: '财运平稳，适合保守投资。',
        healthWarning: {
          level: 'medium',
          description: '梅雨季节，易患湿热症状。',
          suggestions: ['避免潮湿环境', '清淡饮食', '适度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 7,
        overallScore: 68,
        overallDescription: '盛夏时节，运势平稳。需要调整策略。',
        careerScore: 70,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 65,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 65,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '盛夏炎热，易中暑和疲劳。',
          suggestions: ['避免过度劳累', '多喝水', '定期休息', '避免过度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕'],
        },
      },
      {
        month: 8,
        overallScore: 70,
        overallDescription: '立秋时节，运势开始回升。适合新的开始。',
        careerScore: 72,
        careerDescription: '职场机遇增多，有升职的可能。',
        loveScore: 68,
        loveDescription: '感情运势回升，有新的发展。',
        wealthScore: 70,
        wealthDescription: '财运回升，适合投资。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 9,
        overallScore: 72,
        overallDescription: '秋高气爽，运势稳定上升。适合开展新项目。',
        careerScore: 75,
        careerDescription: '职场表现优异，有重要机遇。',
        loveScore: 70,
        loveDescription: '感情甜蜜，有结婚的可能。',
        wealthScore: 72,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '秋季气候宜人，健康状况良好。',
          suggestions: ['适度运动', '调理脾胃', '增强体质'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '保持谦虚'],
        },
      },
      {
        month: 10,
        overallScore: 70,
        overallDescription: '深秋时节，运势平稳。适合巩固成果。',
        careerScore: 72,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 68,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 70,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨言慎行', '避免冲动', '保持低调'],
        },
      },
      {
        month: 11,
        overallScore: 68,
        overallDescription: '初冬时节，运势开始下降。需要调整策略。',
        careerScore: 70,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 65,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 65,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'medium',
          description: '初冬季节，易患感冒。',
          suggestions: ['增加衣物', '避免受风', '增强体质'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 12,
        overallScore: 65,
        overallDescription: '严冬时节，运势较弱。适合休整和反思。',
        careerScore: 65,
        careerDescription: '工作进展缓慢，需要耐心等待。',
        loveScore: 60,
        loveDescription: '感情稳定，但需要更多沟通。',
        wealthScore: 60,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '严冬季节，易患感冒和冻伤。',
          suggestions: ['做好保暖', '避免受风', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'high',
          description: '本月需特别注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕', '避免冲动'],
        },
      },
    ],
    videoRecords: [
      {
        id: '1',
        masterId: 'master-001',
        masterName: '李命理师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2023-01-15',
        duration: '45分钟',
        title: '2023年八字运势分析',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/39778aee-fcdd-4ba0-b542-c2ad6f5c9819.png',
        notes: '整体运势平稳，需要把握机遇。建议多参加社交活动。',
      },
      {
        id: '2',
        masterId: 'master-002',
        masterName: '王紫微师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2023-03-20',
        duration: '60分钟',
        title: '紫微斗数详解',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/c66d419b-d022-4096-963f-d4f37ae1224d.png',
        notes: '命宫主星为紫微，事业运势良好。',
      },
      {
        id: '3',
        masterId: 'master-003',
        masterName: '张占星师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2023-05-10',
        duration: '50分钟',
        title: '西方占星运势预测',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/a5974b26-c507-42f2-afc1-3720bac12162.png',
      },
    ],
  },
  2024: {
    year: 2024,
    months: [
      {
        month: 1,
        overallScore: 72,
        overallDescription: '新年伊始，运势上升。适合制定新的计划和目标。',
        careerScore: 75,
        careerDescription: '工作机遇增多，职场表现突出。',
        loveScore: 70,
        loveDescription: '感情运平稳，有新的发展机会。',
        wealthScore: 72,
        wealthDescription: '财运稳定，适合投资理财。',
        healthWarning: {
          level: 'low',
          description: '整体健康状况良好，无特殊预警。',
          suggestions: ['保持规律作息', '适度运动', '均衡饮食'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月无重大凶险，可放心行动。',
          suggestions: ['出行注意安全', '避免冲动消费', '谨慎签署合同'],
        },
      },
      {
        month: 2,
        overallScore: 75,
        overallDescription: '春节期间运势良好，家庭和睦，事业顺利。',
        careerScore: 78,
        careerDescription: '职场表现突出，有升职加薪的机会。',
        loveScore: 72,
        loveDescription: '感情甜蜜，已婚者家庭和谐。',
        wealthScore: 75,
        wealthDescription: '财运旺盛，有意外收获。',
        healthWarning: {
          level: 'low',
          description: '春节期间注意饮食，避免过度劳累。',
          suggestions: ['控制饮食', '适度休息', '避免熬夜'],
        },
        disasterWarning: {
          level: 'medium',
          description: '春节出行需注意交通安全。',
          suggestions: ['避免长途驾驶', '提前规划路线', '购买保险'],
        },
      },
      {
        month: 3,
        overallScore: 70,
        overallDescription: '春暖花开，运势稳定。适合开展新项目。',
        careerScore: 72,
        careerDescription: '工作进展顺利，团队合作良好。',
        loveScore: 68,
        loveDescription: '感情稳定，可考虑进一步发展。',
        wealthScore: 70,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '春季易感冒，注意增减衣物。',
          suggestions: ['适应气候变化', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨慎投资', '避免冲动决定', '保持低调'],
        },
      },
      {
        month: 4,
        overallScore: 72,
        overallDescription: '清明时节，运势继续上升。适合出行和社交。',
        careerScore: 74,
        careerDescription: '职场机遇增多，人脉拓展良好。',
        loveScore: 72,
        loveDescription: '感情运势上升，有结婚的可能。',
        wealthScore: 74,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '清明时节气候多变，注意保暖。',
          suggestions: ['避免过度劳累', '适度运动', '调理脾胃'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['出行注意安全', '避免争执', '保持谦虚'],
        },
      },
      {
        month: 5,
        overallScore: 78,
        overallDescription: '五月运势最佳，各方面都有突破。',
        careerScore: 82,
        careerDescription: '职场表现优异，有重要机遇出现。',
        loveScore: 78,
        loveDescription: '感情甜蜜，有结婚或订婚的可能。',
        wealthScore: 80,
        wealthDescription: '财运旺盛，投资收益显著。',
        healthWarning: {
          level: 'low',
          description: '五月天气炎热，注意防暑降温。',
          suggestions: ['避免中暑', '多喝水', '适度休息'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势最佳，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 6,
        overallScore: 74,
        overallDescription: '初夏时节，运势稳定。适合巩固成果。',
        careerScore: 76,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 72,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 72,
        wealthDescription: '财运平稳，适合保守投资。',
        healthWarning: {
          level: 'medium',
          description: '梅雨季节，易患湿热症状。',
          suggestions: ['避免潮湿环境', '清淡饮食', '适度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 7,
        overallScore: 70,
        overallDescription: '盛夏时节，运势平稳。需要调整策略。',
        careerScore: 72,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 68,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 68,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '盛夏炎热，易中暑和疲劳。',
          suggestions: ['避免过度劳累', '多喝水', '定期休息', '避免过度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕'],
        },
      },
      {
        month: 8,
        overallScore: 72,
        overallDescription: '立秋时节，运势开始回升。适合新的开始。',
        careerScore: 74,
        careerDescription: '职场机遇增多，有升职的可能。',
        loveScore: 70,
        loveDescription: '感情运势回升，有新的发展。',
        wealthScore: 72,
        wealthDescription: '财运回升，适合投资。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 9,
        overallScore: 74,
        overallDescription: '秋高气爽，运势稳定上升。适合开展新项目。',
        careerScore: 76,
        careerDescription: '职场表现优异，有重要机遇。',
        loveScore: 72,
        loveDescription: '感情甜蜜，有结婚的可能。',
        wealthScore: 74,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '秋季气候宜人，健康状况良好。',
          suggestions: ['适度运动', '调理脾胃', '增强体质'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '保持谦虚'],
        },
      },
      {
        month: 10,
        overallScore: 72,
        overallDescription: '深秋时节，运势平稳。适合巩固成果。',
        careerScore: 74,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 70,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 72,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨言慎行', '避免冲动', '保持低调'],
        },
      },
      {
        month: 11,
        overallScore: 70,
        overallDescription: '初冬时节，运势开始下降。需要调整策略。',
        careerScore: 72,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 68,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 68,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'medium',
          description: '初冬季节，易患感冒。',
          suggestions: ['增加衣物', '避免受风', '增强体质'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 12,
        overallScore: 68,
        overallDescription: '严冬时节，运势较弱。适合休整和反思。',
        careerScore: 68,
        careerDescription: '工作进展缓慢，需要耐心等待。',
        loveScore: 65,
        loveDescription: '感情稳定，但需要更多沟通。',
        wealthScore: 65,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '严冬季节，易患感冒和冻伤。',
          suggestions: ['做好保暖', '避免受风', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'high',
          description: '本月需特别注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕', '避免冲动'],
        },
      },
    ],
    videoRecords: [
      {
        id: '4',
        masterId: 'master-001',
        masterName: '李命理师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2024-02-14',
        duration: '55分钟',
        title: '2024年八字运势分析',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/87298f63-5f5a-49f3-a15c-827be09f2118.png',
        notes: '今年运势整体向好，特别是事业运。建议把握上半年的机遇。',
      },
      {
        id: '5',
        masterId: 'master-002',
        masterName: '王紫微师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2024-05-20',
        duration: '65分钟',
        title: '紫微斗数详解与运势预测',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/f1abd605-6bfd-4cb5-a62d-010d4f60fa71.png',
        notes: '命宫主星为紫微，今年有重要的人生转折。',
      },
    ],
  },
  2025: {
    year: 2025,
    months: [
      {
        month: 1,
        overallScore: 75,
        overallDescription: '新年伊始，运势上升。适合制定新的计划和目标。',
        careerScore: 78,
        careerDescription: '工作机遇增多，职场表现突出。',
        loveScore: 72,
        loveDescription: '感情运平稳，有新的发展机会。',
        wealthScore: 75,
        wealthDescription: '财运稳定，适合投资理财。',
        healthWarning: {
          level: 'low',
          description: '整体健康状况良好，无特殊预警。',
          suggestions: ['保持规律作息', '适度运动', '均衡饮食'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月无重大凶险，可放心行动。',
          suggestions: ['出行注意安全', '避免冲动消费', '谨慎签署合同'],
        },
      },
      {
        month: 2,
        overallScore: 78,
        overallDescription: '春节期间运势良好，家庭和睦，事业顺利。',
        careerScore: 80,
        careerDescription: '职场表现突出，有升职加薪的机会。',
        loveScore: 75,
        loveDescription: '感情甜蜜，已婚者家庭和谐。',
        wealthScore: 78,
        wealthDescription: '财运旺盛，有意外收获。',
        healthWarning: {
          level: 'low',
          description: '春节期间注意饮食，避免过度劳累。',
          suggestions: ['控制饮食', '适度休息', '避免熬夜'],
        },
        disasterWarning: {
          level: 'medium',
          description: '春节出行需注意交通安全。',
          suggestions: ['避免长途驾驶', '提前规划路线', '购买保险'],
        },
      },
      {
        month: 3,
        overallScore: 73,
        overallDescription: '春暖花开，运势稳定。适合开展新项目。',
        careerScore: 75,
        careerDescription: '工作进展顺利，团队合作良好。',
        loveScore: 70,
        loveDescription: '感情稳定，可考虑进一步发展。',
        wealthScore: 73,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '春季易感冒，注意增减衣物。',
          suggestions: ['适应气候变化', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨慎投资', '避免冲动决定', '保持低调'],
        },
      },
      {
        month: 4,
        overallScore: 75,
        overallDescription: '清明时节，运势继续上升。适合出行和社交。',
        careerScore: 77,
        careerDescription: '职场机遇增多，人脉拓展良好。',
        loveScore: 75,
        loveDescription: '感情运势上升，有结婚的可能。',
        wealthScore: 77,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '清明时节气候多变，注意保暖。',
          suggestions: ['避免过度劳累', '适度运动', '调理脾胃'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['出行注意安全', '避免争执', '保持谦虚'],
        },
      },
      {
        month: 5,
        overallScore: 80,
        overallDescription: '五月运势最佳，各方面都有突破。',
        careerScore: 85,
        careerDescription: '职场表现优异，有重要机遇出现。',
        loveScore: 80,
        loveDescription: '感情甜蜜，有结婚或订婚的可能。',
        wealthScore: 82,
        wealthDescription: '财运旺盛，投资收益显著。',
        healthWarning: {
          level: 'low',
          description: '五月天气炎热，注意防暑降温。',
          suggestions: ['避免中暑', '多喝水', '适度休息'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势最佳，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 6,
        overallScore: 76,
        overallDescription: '初夏时节，运势稳定。适合巩固成果。',
        careerScore: 78,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 74,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 76,
        wealthDescription: '财运平稳，适合保守投资。',
        healthWarning: {
          level: 'medium',
          description: '梅雨季节，易患湿热症状。',
          suggestions: ['避免潮湿环境', '清淡饮食', '适度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 7,
        overallScore: 72,
        overallDescription: '盛夏时节，运势平稳。需要调整策略。',
        careerScore: 74,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 70,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 70,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '盛夏炎热，易中暑和疲劳。',
          suggestions: ['避免过度劳累', '多喝水', '定期休息', '避免过度运动'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕'],
        },
      },
      {
        month: 8,
        overallScore: 74,
        overallDescription: '立秋时节，运势开始回升。适合新的开始。',
        careerScore: 76,
        careerDescription: '职场机遇增多，有升职的可能。',
        loveScore: 72,
        loveDescription: '感情运势回升，有新的发展。',
        wealthScore: 74,
        wealthDescription: '财运回升，适合投资。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，可放心行动。',
          suggestions: ['把握机遇', '积极行动', '谨慎理财'],
        },
      },
      {
        month: 9,
        overallScore: 76,
        overallDescription: '秋高气爽，运势稳定上升。适合开展新项目。',
        careerScore: 78,
        careerDescription: '职场表现优异，有重要机遇。',
        loveScore: 74,
        loveDescription: '感情甜蜜，有结婚的可能。',
        wealthScore: 76,
        wealthDescription: '财运旺盛，投资有收益。',
        healthWarning: {
          level: 'low',
          description: '秋季气候宜人，健康状况良好。',
          suggestions: ['适度运动', '调理脾胃', '增强体质'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势良好，无重大凶险。',
          suggestions: ['把握机遇', '积极行动', '保持谦虚'],
        },
      },
      {
        month: 10,
        overallScore: 74,
        overallDescription: '深秋时节，运势平稳。适合巩固成果。',
        careerScore: 76,
        careerDescription: '工作稳定，有晋升的可能。',
        loveScore: 72,
        loveDescription: '感情稳定，可考虑重要决定。',
        wealthScore: 74,
        wealthDescription: '财运平稳，适合理财规划。',
        healthWarning: {
          level: 'low',
          description: '秋季干燥，注意补水保湿。',
          suggestions: ['多喝水', '滋阴润肺', '适度运动'],
        },
        disasterWarning: {
          level: 'low',
          description: '本月运势平稳，无重大凶险。',
          suggestions: ['谨言慎行', '避免冲动', '保持低调'],
        },
      },
      {
        month: 11,
        overallScore: 72,
        overallDescription: '初冬时节，运势开始下降。需要调整策略。',
        careerScore: 74,
        careerDescription: '工作进展顺利，但需要更多耐心。',
        loveScore: 70,
        loveDescription: '感情稳定，可能有小波澜。',
        wealthScore: 70,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'medium',
          description: '初冬季节，易患感冒。',
          suggestions: ['增加衣物', '避免受风', '增强体质'],
        },
        disasterWarning: {
          level: 'medium',
          description: '本月需注意人际关系，避免冲突。',
          suggestions: ['谨言慎行', '避免争执', '保持低调'],
        },
      },
      {
        month: 12,
        overallScore: 70,
        overallDescription: '严冬时节，运势较弱。适合休整和反思。',
        careerScore: 70,
        careerDescription: '工作进展缓慢，需要耐心等待。',
        loveScore: 67,
        loveDescription: '感情稳定，但需要更多沟通。',
        wealthScore: 67,
        wealthDescription: '财运平稳，避免大额投资。',
        healthWarning: {
          level: 'high',
          description: '严冬季节，易患感冒和冻伤。',
          suggestions: ['做好保暖', '避免受风', '增强体质', '定期体检'],
        },
        disasterWarning: {
          level: 'high',
          description: '本月需特别注意安全，避免意外。',
          suggestions: ['避免危险活动', '谨慎驾驶', '保持警惕', '避免冲动'],
        },
      },
    ],
    videoRecords: [
      {
        id: '6',
        masterId: 'master-001',
        masterName: '李命理师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2025-01-10',
        duration: '50分钟',
        title: '2025年八字运势分析',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/ba9a9d33-e0c7-48d3-aa29-d0c74e7dcb68.png',
        notes: '2025年整体运势向好，特别是上半年。建议把握机遇。',
      },
      {
        id: '7',
        masterId: 'master-003',
        masterName: '张占星师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2025-02-15',
        duration: '60分钟',
        title: '西方占星2025年运势预测',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/dd94f0da-3090-420b-9fe1-0bae7bae5da9.png',
        notes: '木星进入新宫位，带来新的机遇和挑战。',
      },
      {
        id: '8',
        masterId: 'master-002',
        masterName: '王紫微师',
        masterAvatar: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/11/12/f3559455-67d0-4e45-b60a-909f00bc66b3.png',
        date: '2025-03-20',
        duration: '70分钟',
        title: '紫微斗数2025年详解',
        thumbnail: 'https://spark-builder.s3.us-east-1.amazonaws.com/image/2025/12/12/09ae302d-00d3-46a2-b730-3c6507e1a213.png',
        notes: '今年有重要的人生转折，需要做好准备。',
      },
    ],
  },
};
